version: "3.9"
services:
  db:
    image: postgres:16
    container_name: monitoring_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-metrics}
    ports:
      - "5433:5432" # host:container
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: monitoring_app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ["/app/server"]

volumes:
  dbdata: